@CourtRoom_HostAddress = http://localhost:5205

POST {{CourtRoom_HostAddress}}/Auth/Register
Accept: application/json
Content-Type: application/json

{
  "Name": "Cashier User",
  "Email": "cashier",
  "Password": "cashier123",
  "Role": "Cashier"
}

###
POST {{CourtRoom_HostAddress}}/Auth/Login
Accept: application/json
Content-Type: application/json

{
  "Email": "admin",
  "Password": "admin123"
}


###
GET {{CourtRoom_HostAddress}}/Auth
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4gVXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NDQ4OTc1NDcsImlzcyI6InNoaXZhIiwiYXVkIjoic3RhcmsifQ.XOAFGAHbiEjqDfIrhjQEvkQPQYzcYHBdQgrqH2RcKH8