// <auto-generated />
using System;
using CourtRoom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourtRoom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250406164147_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourtRoom.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CourtRoom.Models.CourtOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CashWhereToBeDeposited")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CauseListSlNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CostImposed")
                        .HasColumnType("double precision");

                    b.Property<string>("CourtDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourtNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImposedOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CourtOrders");
                });

            modelBuilder.Entity("CourtRoom.Models.PaymentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CostDeposited")
                        .HasColumnType("double precision");

                    b.Property<int>("CourtOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfCatBarLibFund")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfDeposit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentRefNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourtOrderId")
                        .IsUnique();

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("CourtRoom.Models.PaymentDetail", b =>
                {
                    b.HasOne("CourtRoom.Models.CourtOrder", "CourtOrder")
                        .WithOne("PaymentDetail")
                        .HasForeignKey("CourtRoom.Models.PaymentDetail", "CourtOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourtOrder");
                });

            modelBuilder.Entity("CourtRoom.Models.CourtOrder", b =>
                {
                    b.Navigation("PaymentDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
